# -*- coding: utf-8 -*-
"""app_analisis_transaksi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17yEKDhRgQt4u1DhBw6cvJYHYztJ1EcIH
"""
import sys
import packaging.version
import sklearn
#import yellowbrick
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, accuracy_score, classification_report
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# --- PERPUSTAKAAN ELBOW ---
# from yellowbrick.cluster import KElbowVisualizer

import joblib
import os
import warnings
warnings.filterwarnings('ignore')

# =======================
# KONFIGURASI AWAL APLIKASI
# =======================
st.set_page_config(
    page_title="Analisis Transaksi & Deteksi Penipuan",
    page_icon="💳",
    layout="wide"
)

# =======================
# FUNGSI: TAHAP 1 - CLUSTERING
# =======================
def proses_clustering(data_baru=None):
    if data_baru is None:
        url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTbg5WVW6W3c8SPNUGc3A3AL-AG32TPEQGpdzARfNICMsLFI0LQj0jporhsLCeVhkN5AoRsTkn08AYl/pub?output=csv'
        df = pd.read_csv(url)
    else:
        df = data_baru.copy()

    # PEMBERSIHAN DATA
    df.dropna(inplace=True)
    df.drop_duplicates(inplace=True)

    # Hapus kolom tidak relevan
    cols_to_drop = [col for col in df.columns if 'id' in col.lower() or 'ip' in col.lower() or 'date' in col.lower()]
    df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

    # Simpan daftar kolom
    numerical_cols = df.select_dtypes(include=['number']).columns
    categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

    # ENCODING
    encoders = {}
    for col in categorical_cols:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        encoders[col] = le

    # Binning Usia
    if 'CustomerAge' in df.columns:
        df['AgeGroup'] = pd.qcut(df['CustomerAge'].replace(0, np.nan), q=3, labels=['Muda', 'Dewasa', 'Tua'], duplicates='drop')
        df['AgeGroup'] = df['AgeGroup'].cat.add_categories(['Tidak Diketahui']).fillna('Tidak Diketahui')
        le_age = LabelEncoder()
        df['AgeGroup'] = le_age.fit_transform(df['AgeGroup'])
        encoders['AgeGroup'] = le_age
        categorical_cols.append('AgeGroup')

    # Simpan Data Eksplorasi (Data asli setelah dibersihkan)
    df_eksplorasi = df.copy()

    # HANDLING OUTLIER
    for col in numerical_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

    # SCALING
    scaler = StandardScaler()
    df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

    # Data khusus untuk Elbow Method (Hanya data numerik yang sudah bersih & skala)
    df_untuk_elbow = df[numerical_cols].copy()

    # MODEL KMEANS
    model = KMeans(n_clusters=3, random_state=42, n_init='auto')
    model.fit(df)
    df['Target'] = model.labels_

    # PCA UNTUK VISUALISASI
    pca = PCA(n_components=2)
    pca_result = pca.fit_transform(df.drop('Target', axis=1))
    df['PCA1'] = pca_result[:, 0]
    df['PCA2'] = pca_result[:, 1]

    # ANALISIS BALIK KE NILAI ASLI
    df_inverse = df.copy()
    df_inverse[numerical_cols] = scaler.inverse_transform(df_inverse[numerical_cols])
    for col in encoders:
        if col in df_inverse.columns:
            df_inverse[col] = encoders[col].inverse_transform(df_inverse[col].astype(int))

    # Simpan file CSV untuk bahan klasifikasi
    df.to_csv("data_clustering.csv", index=False)

    return df, df_inverse, df_eksplorasi, df_untuk_elbow, numerical_cols, categorical_cols

# =======================
# FUNGSI: TAHAP 2 - KLASIFIKASI
# =======================
def proses_klasifikasi():
    # Cek apakah file hasil clustering ada
    if not os.path.exists("data_clustering.csv"):
        return None, None, None, None, None

    # 1. Load Data
    df = pd.read_csv("data_clustering.csv")

    # 2. Encoding Kategori
    categorical_cols = list(df.select_dtypes(include=['object']).columns)
    df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

    # 3. Pembagian Data
    X = df_encoded.drop('Target', axis=1)
    y = df_encoded['Target']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # 4. Pembuatan Model
    # Decision Tree
    dt_model = DecisionTreeClassifier(random_state=42)
    dt_model.fit(X_train, y_train)
    y_pred_dt = dt_model.predict(X_test)
    report_dt_dict = classification_report(y_test, y_pred_dt, output_dict=True)
    report_dt_text = classification_report(y_test, y_pred_dt)

    # Random Forest
    rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
    rf_model.fit(X_train, y_train)
    y_pred_rf = rf_model.predict(X_test)
    report_rf_dict = classification_report(y_test, y_pred_rf, output_dict=True)
    report_rf_text = classification_report(y_test, y_pred_rf)

    # 5. Hyperparameter Tuning
    params = {
        'max_depth': [3, 5, 10],
        'min_samples_split': [2, 5, 10],
        'criterion': ['gini', 'entropy'],
    }
    tuned_model = GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), param_grid=params, cv=5, scoring='accuracy')
    tuned_model.fit(X_train, y_train)
    y_pred_tuned = tuned_model.predict(X_test)
    report_tuned_dict = classification_report(y_test, y_pred_tuned, output_dict=True)
    report_tuned_text = classification_report(y_test, y_pred_tuned)

    # 6. Simpan Model
    joblib.dump(dt_model, 'decision_tree_model.h5')
    joblib.dump(rf_model, 'random_forest_model.h5')
    joblib.dump(tuned_model, 'tuned_classification_model.h5')

    return dt_model, rf_model, tuned_model, report_dt_dict, report_rf_dict, report_tuned_dict, report_dt_text, report_rf_text, report_tuned_text, X

# =======================
# TAMPILAN APLIKASI
# =======================

st.title("💳 Aplikasi Analisis Transaksi:     Clustering & Klasifikasi")
st.markdown("Sistem lengkap: Mulai dari pengelompokan otomatis hingga prediksi kecerdasan buatan.")

# Sidebar Menu
menu = st.sidebar.selectbox(
    "Pilih Menu",
    ["🏠 Beranda", "🔬 Eksplorasi Data", "📊 Hasil Clustering", "📈 Visualisasi PCA", "🤖 Model Klasifikasi", "🔍 Prediksi Cerdas"]
)

# ----------------------
# MENU: BERANDA
# ----------------------
if menu == "🏠 Beranda":
    st.header("Selamat Datang")
    st.info("""
    **ALUR KERJA SISTEM:**
    1. **Clustering (Unsupervised):** Mengelompokkan transaksi menjadi Normal / Kurang Aman / Mencurigakan.
    2. **Klasifikasi (Supervised):** Melatih AI untuk memprediksi kategori transaksi baru berdasarkan pola yang sudah dipelajari.

    **Langkah Penggunaan:**
    1. Tekan tombol **Jalankan Analisis** di bawah.
    2. Tunggu proses selesai.
    3. Eksplorasi menu di samping.
    """)

    if st.button("🔄 MULAI: Jalankan Semua Proses", type="primary"):
        with st.spinner("Sedang memproses data tahap 1: Clustering..."):
            df_olah, df_asli, df_eksplorasi, df_untuk_elbow, num_cols, cat_cols = proses_clustering()

            st.session_state['df_olah'] = df_olah
            st.session_state['df_asli'] = df_asli
            st.session_state['df_eksplorasi'] = df_eksplorasi
            st.session_state['df_untuk_elbow'] = df_untuk_elbow
            st.session_state['num_cols'] = num_cols
            st.session_state['cat_cols'] = cat_cols

        with st.spinner("Sedang memproses data tahap 2: Membuat Model Prediksi..."):
            hasil_klasifikasi = proses_klasifikasi()
            if hasil_klasifikasi[0] is not None:
                dt_model, rf_model, tuned_model, report_dt_dict, report_rf_dict, report_tuned_dict, report_dt_text, report_rf_text, report_tuned_text, X = hasil_klasifikasi

                st.session_state['dt_model'] = dt_model
                st.session_state['rf_model'] = rf_model
                st.session_state['tuned_model'] = tuned_model

                st.session_state['report_dt_dict'] = report_dt_dict
                st.session_state['report_rf_dict'] = report_rf_dict
                st.session_state['report_tuned_dict'] = report_tuned_dict

                st.session_state['report_dt_text'] = report_dt_text
                st.session_state['report_rf_text'] = report_rf_text
                st.session_state['report_tuned_text'] = report_tuned_text

                st.session_state['features'] = X.columns

        st.success("✅ **SELESAI!** Semua model telah dibuat dan siap digunakan.")
        st.balloons()

# Cek Status Data
data_siap = 'df_asli' in st.session_state
model_siap = 'dt_model' in st.session_state

# ----------------------
# MENU: EKSPLORASI DATA (DIPERBAIKI ELBOW SESUAI KODE ASLIMU)
# ----------------------
if menu == "🔬 Eksplorasi Data":
    if not data_siap:
        st.warning("⚠️ Jalankan proses di Beranda terlebih dahulu!")
    else:
        df_eksplorasi = st.session_state['df_eksplorasi']
        df_untuk_elbow = st.session_state['df_untuk_elbow']
        numerical_cols = st.session_state['num_cols']

        st.header("🔍 Analisis Awal Data")

        # Korelasi
        st.subheader("📌 Matriks Korelasi")
        correlation = df_eksplorasi[numerical_cols].corr()
        fig_corr, ax_corr = plt.subplots(figsize=(10, 6))
        sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt=".2f", vmin=-1, vmax=1, ax=ax_corr)
        st.pyplot(fig_corr, use_container_width=True)

        st.divider()

        # Histogram
        st.subheader("📌 Sebaran Nilai (Histogram)")
        jumlah_kolom = len(numerical_cols)
        baris = (jumlah_kolom // 3) + (1 if jumlah_kolom % 3 != 0 else 0)
        fig_hist, axes = plt.subplots(baris, 3, figsize=(18, 5 * baris))
        axes = axes.flatten()

        for i, column in enumerate(numerical_cols):
            sns.histplot(df_eksplorasi[column], bins=20, kde=True, color='skyblue', ax=axes[i])
            axes[i].set_title(column)
            axes[i].set_xlabel("Nilai")
            axes[i].set_ylabel("Frekuensi")
        for j in range(i+1, len(axes)): axes[j].axis('off')

        plt.tight_layout()
        st.pyplot(fig_hist, use_container_width=True)

        st.divider()

        # --- VISUALISASI BARU: BOXPLOT PEKERJAAN ---
        st.subheader("📌 Nilai Transaksi Berdasarkan Pekerjaan")
        if 'CustomerOccupation' in df_eksplorasi.columns and 'TransactionAmount' in df_eksplorasi.columns:
            fig_box, ax_box = plt.subplots(figsize=(12, 6))

            # Kode kamu persis dimasukkan di sini
            sns.boxplot(x="CustomerOccupation", y="TransactionAmount", data=df_eksplorasi, ax=ax_box)
            ax_box.set_title("Nilai Transaksi per Pekerjaan Nasabah (Boxplot)")
            plt.xticks(rotation=45) # Putar label agar tidak tumpang tindih

            st.pyplot(fig_box, use_container_width=True)
        else:
            st.info("⚠️ Kolom 'CustomerOccupation' atau 'TransactionAmount' tidak ditemukan dalam data.")

        st.divider()

        # --- ELBOW METHOD ---
        # --- ELBOW METHOD (MANUAL, TANPA YELLOWBRICK) ---
        st.subheader("📌 Penentuan Jumlah Cluster Terbaik (Elbow Method)")
        st.markdown("Metode Silhouette Score: Nilai tertinggi menunjukkan jumlah kelompok yang paling optimal.")

        fig_elbow, ax_elbow = plt.subplots(figsize=(10, 6))
        sil_scores = []
        k_list = range(2, 10)

        for k in k_list:
            km = KMeans(n_clusters=k, random_state=42, n_init='auto')
            lbl = km.fit_predict(df_untuk_elbow)
            sil_scores.append(silhouette_score(df_untuk_elbow, lbl))

        ax_elbow.plot(k_list, sil_scores, 'bo-', linewidth=2, markersize=8)
        ax_elbow.set_xlabel("Jumlah Cluster (k)")
        ax_elbow.set_ylabel("Silhouette Score")
        ax_elbow.set_title("Penentuan Jumlah Cluster Terbaik")
        ax_elbow.grid(True)

        best_k = k_list[sil_scores.index(max(sil_scores))]
        ax_elbow.scatter([best_k], [max(sil_scores)], c='red', s=150, label=f"Terbaik: k={best_k}")
        ax_elbow.legend()

        st.pyplot(fig_elbow, use_container_width=True)

# ----------------------
# MENU: HASIL CLUSTERING
# ----------------------
if menu == "📊 Hasil Clustering":
    if not data_siap:
        st.warning("⚠️ Jalankan proses di Beranda terlebih dahulu!")
    else:
        df_asli = st.session_state['df_asli']
        st.header("Hasil Pengelompokan Transaksi")

        st.subheader("Jumlah Anggota Per Kelompok")
        jumlah_cluster = df_asli['Target'].value_counts().sort_index()
        st.bar_chart(jumlah_cluster, use_container_width=True)

        st.subheader("Karakteristik Kelompok")
        ringkasan = df_asli.groupby('Target')[st.session_state['num_cols']].agg(['mean', 'min', 'max']).round(2)
        st.dataframe(ringkasan, use_container_width=True)

        st.subheader("Data Lengkap")
        st.dataframe(df_asli)
        st.download_button("💾 Download Data", data=df_asli.to_csv(index=False).encode('utf-8'), file_name='hasil_clustering_akhir.csv')

# ----------------------
# MENU: VISUALISASI PCA
# ----------------------
if menu == "📈 Visualisasi PCA":
    if not data_siap:
        st.warning("⚠️ Jalankan proses di Beranda terlebih dahulu!")
    else:
        df_olah = st.session_state['df_olah']
        st.header("Pemetaan Sebaran 2 Dimensi")
        fig, ax = plt.subplots(figsize=(10, 6))
        sns.scatterplot(data=df_olah, x='PCA1', y='PCA2', hue='Target', palette=['green', 'orange', 'red'], s=100, ax=ax)
        st.pyplot(fig, use_container_width=True)

# ----------------------
# MENU: KLASIFIKASI
# ----------------------
if menu == "🤖 Model Klasifikasi":
    if not model_siap:
        st.warning("⚠️ Jalankan proses di Beranda terlebih dahulu!")
    else:
        st.header("📊 Performa Model Prediksi")
        st.markdown("Evaluasi akurasi, presisi, recall, dan F1-Score dari setiap algoritma.")

        tab1, tab2, tab3 = st.tabs(["🌳 Decision Tree", "🌲 Random Forest", "⚙️ Decision Tree + Tuning"])

        with tab1:
            st.subheader("Decision Tree")
            report_dict = st.session_state['report_dt_dict']
            df_report = pd.DataFrame(report_dict).transpose().round(2)
            df_report = df_report.reset_index()
            df_report.columns = ['Kelas', 'Presisi', 'Recall', 'F1-Score', 'Jumlah Data']
            df_report = df_report[df_report['Kelas'].isin(['0', '1', '2', 'accuracy', 'macro avg', 'weighted avg'])]
            st.dataframe(df_report, use_container_width=True)
            st.code(st.session_state['report_dt_text'], language='text')

        with tab2:
            st.subheader("Random Forest")
            report_dict = st.session_state['report_rf_dict']
            df_report = pd.DataFrame(report_dict).transpose().round(2)
            df_report = df_report.reset_index()
            df_report.columns = ['Kelas', 'Presisi', 'Recall', 'F1-Score', 'Jumlah Data']
            df_report = df_report[df_report['Kelas'].isin(['0', '1', '2', 'accuracy', 'macro avg', 'weighted avg'])]
            st.dataframe(df_report, use_container_width=True)
            st.code(st.session_state['report_rf_text'], language='text')

        with tab3:
            st.subheader("Decision Tree + Tuning")
            report_dict = st.session_state['report_tuned_dict']
            df_report = pd.DataFrame(report_dict).transpose().round(2)
            df_report = df_report.reset_index()
            df_report.columns = ['Kelas', 'Presisi', 'Recall', 'F1-Score', 'Jumlah Data']
            df_report = df_report[df_report['Kelas'].isin(['0', '1', '2', 'accuracy', 'macro avg', 'weighted avg'])]
            st.dataframe(df_report, use_container_width=True)
            st.code(st.session_state['report_tuned_text'], language='text')

# ----------------------
# MENU: PREDIKSI CERDAS (SUDAH GANTI KE CHECKBOX & BERJALAN)
# ----------------------
if menu == "🔍 Prediksi Cerdas":
    if not model_siap:
        st.warning("⚠️ Jalankan proses di Beranda terlebih dahulu!")
    else:
        st.header("🔎 Prediksi Transaksi Baru")
        st.markdown("Masukkan data transaksi di bawah ini, sistem akan memprediksi apakah transaksi tersebut Aman, Kurang Aman, atau Mencurigakan.")

        # ✅ SUDAH GANTI KE CHECKBOX, TIDAK ADA DROPDOWN LAGI
        st.subheader("Pilih Model Prediksi")
        model_dt = st.checkbox("🌳 Decision Tree", value=True)
        model_rf = st.checkbox("🌲 Random Forest", value=True)
        model_tune = st.checkbox("⚙️ Model Terbaik (Tuning)", value=True)

        st.divider()

        # Input Data
        col1, col2, col3 = st.columns(3)
        with col1:
            amt = st.number_input("Nilai Transaksi", min_value=0.0, value=150000.0)
            bal = st.number_input("Saldo Akun", min_value=0.0, value=1000000.0)
        with col2:
            dur = st.number_input("Durasi (detik)", min_value=0, value=45)
            age = st.number_input("Usia Nasabah", min_value=17, max_value=90, value=30)
        with col3:
            login = st.number_input("Percobaan Login", min_value=1, max_value=10, value=1)
            type_opt = st.selectbox("Tipe Transaksi", ["Debit", "Credit"])
            chan_opt = st.selectbox("Kanal", ["ATM", "Online", "Branch"])

        # Proses Prediksi
        if st.button("🚀 PREDIKSI SEKARANG", type="primary"):

            features_list = st.session_state['features']
            input_data = pd.DataFrame(columns=features_list, index=[0])
            input_data = input_data.fillna(0.0)

            # Isi nilai numerik
            if 'TransactionAmount' in features_list: input_data['TransactionAmount'] = amt
            if 'AccountBalance' in features_list: input_data['AccountBalance'] = bal
            if 'TransactionDuration' in features_list: input_data['TransactionDuration'] = dur
            if 'CustomerAge' in features_list: input_data['CustomerAge'] = age
            if 'LoginAttempts' in features_list: input_data['LoginAttempts'] = login

            # Isi nilai kategorikal
            if f'TransactionType_{type_opt}' in features_list: input_data[f'TransactionType_{type_opt}'] = 1
            if f'Channel_{chan_opt}' in features_list: input_data[f'Channel_{chan_opt}'] = 1

            st.markdown("---")
            st.subheader("📋 Hasil Prediksi")

            # Tampilkan hasil hanya untuk kotak yang dicentang
            if model_dt:
                hasil_dt = st.session_state['dt_model'].predict(input_data)[0]
                if hasil_dt == 0:
                    st.success("**🌳 Decision Tree: AMAN / NORMAL**")
                elif hasil_dt == 1:
                    st.warning("**🌳 Decision Tree: KURANG AMAN / PERLU PERHATIAN**")
                else:
                    st.error("**🌳 Decision Tree: MENCURIGAKAN / BERISIKO TINGGI**")

            if model_rf:
                hasil_rf = st.session_state['rf_model'].predict(input_data)[0]
                if hasil_rf == 0:
                    st.success("**🌲 Random Forest: AMAN / NORMAL**")
                elif hasil_rf == 1:
                    st.warning("**🌲 Random Forest: KURANG AMAN / PERLU PERHATIAN**")
                else:
                    st.error("**🌲 Random Forest: MENCURIGAKAN / BERISIKO TINGGI**")

            if model_tune:
                hasil_tune = st.session_state['tuned_model'].predict(input_data)[0]
                if hasil_tune == 0:
                    st.success("**⚙️ Model Terbaik: AMAN / NORMAL**")
                elif hasil_tune == 1:
                    st.warning("**⚙️ Model Terbaik: KURANG AMAN / PERLU PERHATIAN**")
                else:
                    st.error("**⚙️ Model Terbaik: MENCURIGAKAN / BERISIKO TINGGI**")
